/**
 * Future project brief generator.
 *
 * Takes platform context and recommendations and produces a structured brief
 * for the next experience — formatted as a project prompt.
 *
 * OUTPUT IS DRAFT ONLY:
 *   - This function writes no files
 *   - It makes no commits
 *   - It modifies no code
 *   - The returned string must be reviewed and approved before use
 *
 * Usage:
 *   const brief = generateBrief(context);
 *   console.log(brief); // copy/paste into your next prompt
 */

import type { Recommendation } from './recommendations';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ExistingExperience {
  id: string;
  displayName: string;
  emotionalArc: string;
  colorPrimary: string;
  /** Short description of the Canvas2D renderer (e.g., 'orange particles', 'cyan dot-grid'). */
  renderer: string;
}

export interface BriefContext {
  /** E.g., 'Phase 7'. Used in brief header. */
  platformVersion: string;
  existingExperiences: ExistingExperience[];
  /** Module names safe to reuse without modification. */
  stableModules: string[];
  /** Top recommendations from generateRecommendations(). */
  topRecommendations: Recommendation[];
  /** Optional: human-provided direction hint for the next experience. */
  proposedFocus?: string;
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Generate a draft brief for the next experience on the platform.
 * Returns a markdown string. Does not write or modify any files.
 */
export function generateBrief(context: BriefContext): string {
  const { existingExperiences, stableModules, topRecommendations, proposedFocus } = context;
  const nextPhaseNumber = existingExperiences.length + 4; // Phases 0–3 were engine phases
  const date = new Date().toISOString().split('T')[0];

  const critical = topRecommendations.filter((r) => r.priority === 'critical');
  const high = topRecommendations.filter((r) => r.priority === 'high');
  const hasIssues = critical.length > 0 || high.length > 0;

  const usedColors = existingExperiences.map((e) => e.colorPrimary).join(', ');
  const usedArcs = existingExperiences.map((e) => e.emotionalArc).join(', ');
  const usedRenderers = existingExperiences.map((e) => e.renderer).join(', ');

  return `# Fox Haven Experience Platform — Phase ${nextPhaseNumber} Brief (DRAFT)

**Generated:** ${date}
**Status:** DRAFT — requires human review and approval before use
**Platform version:** ${context.platformVersion}

---

> This brief was generated by the Fox Haven learning loop based on analytics data.
> All [INSERT] fields must be filled in by a human before this brief can be used.
> Recommendations are evidence-based but not authoritative — human judgment governs.

---

## Analytical Foundation

${hasIssues ? buildIssueSection(critical, high) : '> No critical or high-priority issues identified in current analytics data. This brief is proactive.'}

---

## Platform State After ${context.platformVersion}

### Registered Experiences
${existingExperiences.map((e, i) =>
  `${i + 1}. \`${e.id}\` — ${e.displayName}\n   - Emotional arc: ${e.emotionalArc}\n   - Primary color: ${e.colorPrimary}\n   - Renderer: ${e.renderer}`
).join('\n')}

### Visual Grammar Already in Use
- **Primary colors:** ${usedColors} — new experience must choose a distinct primary
- **Emotional arcs:** ${usedArcs} — do not repeat these exactly
- **Canvas renderers:** ${usedRenderers} — new renderer must be visually and mechanically distinct

### Stable Reusable Modules
${stableModules.map((m) => `- \`${m}\``).join('\n')}
These modules require zero changes. Drop them in directly.

---

## Proposed Direction for Phase ${nextPhaseNumber}

${proposedFocus ? `**Human-provided direction:** ${proposedFocus}\n` : ''}
**[INSERT: Product or narrative this experience covers]**
**[INSERT: Emotional arc — must differ from: ${usedArcs}]**
**[INSERT: Canvas2D visual metaphor — must differ from: ${usedRenderers}]**
**[INSERT: Primary color — must differ from: ${usedColors}]**
**[INSERT: How does this address the analytical issues above, if applicable?]**

---

## Operating Rules (inherited — do not modify)

- Do not skip phases
- Do not jump ahead
- Do not redesign unrelated parts of the site
- Do not replace working systems without clear justification
- Keep the site usable throughout
- Keep immersive logic separate from normal site-shell logic
- Prefer reusable abstractions over one-off effects
- Every phase must end with QA notes, limitations, and a handoff

---

## Required Deliverables

### Code
- \`src/experience/scenes/[id]/[Renderer].ts\` — Canvas2D renderer extending Canvas2DRenderer
- \`src/experience/scenes/[id]/manifest.ts\` — ExperienceManifest + SceneManifest
- \`src/experience/scenes/[id]/[Name]Scene.tsx\` — Hybrid scene component
- \`src/experience/scenes/[id]/[Name]Phases.tsx\` — Phase content components + navigation
- \`src/experience/scenes/[id]/[Name]Fallback.tsx\` — CSS-only fallback
- \`src/app/initiatives/[id]/page.tsx\` — Server route page
- Wire \`usePhaseTracking\` into the scene (one line, see analytics/usePhaseTracking.ts)

### Registry
- Add \`registerExperience()\` call in \`src/experience/core/registry.ts\`

### Shell
- Add "Experience the [Name]" Link to the relevant shell section component

### Documentation
- \`[NAME]_NOTES.md\`
- \`[NAME]_QA.md\`
- \`[NAME]_LIMITATIONS.md\`
- \`[NAME]_HANDOFF.md\`

---

## Acceptance Criteria

- \`npx tsc --noEmit\` — 0 errors
- \`experienceManifest.status === 'complete'\`
- \`assetRequirements === []\` (or assets confirmed deliverable)
- Visual grammar is distinct from all ${existingExperiences.length} existing experiences on all three dimensions: color, renderer, emotional arc
- \`usePhaseTracking\` is wired in — analytics events fire on phase navigation
- At least one analytically-identified issue is addressed or explicitly documented as out-of-scope

---

*Generated by Fox Haven Learning Loop · ${context.platformVersion} · ${date}*
*This is a draft. Review all content before use. Do not auto-commit this file.*
`;
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

function buildIssueSection(
  critical: Recommendation[],
  high: Recommendation[]
): string {
  const lines: string[] = [];

  if (critical.length > 0) {
    lines.push('### Critical Issues\n');
    for (const r of critical) {
      lines.push(`**[${r.id}]** Scene: \`${r.sceneId}\``);
      lines.push(`> ${r.evidence}`);
      lines.push(`Recommended action: ${r.recommendedAction}\n`);
    }
  }

  if (high.length > 0) {
    lines.push('### High-Priority Issues\n');
    for (const r of high) {
      lines.push(`**[${r.id}]** Scene: \`${r.sceneId}\``);
      lines.push(`> ${r.evidence}`);
      lines.push(`Recommended action: ${r.recommendedAction}\n`);
    }
  }

  return lines.join('\n');
}
